### ISSUE TITLE
Security rules for firebase DB

### ISSUE THREAD

**Issue by sectem** [ininex/geofire-python#1]
Can you please share security rules you wrote in db, I am not able to identify specific entry in db.

It gives me "Index not defined" error. I have tried alot of stuff but it fails. So it would be big help if you just share security rules

**Comment by ininex** [comment]
Sure, sorry I will also add security rules in readme, thanks for pointing out. Below is the db rules:
`{
    "rules": {
        ".read": true,
        ".write": true,
        "Locations": {
            ".indexOn":"geohash"
        }
    }
}`
